// <auto-generated />
using System;
using System.Collections.Generic;
using LexiCraft.Services.Identity.Shared.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LexiCraft.Services.Identity.Shared.Data.Migrations
{
    [DbContext(typeof(IdentityDbContext))]
    [Migration("20260117152149_updateUser")]
    partial class updateUser
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LexiCraft.Services.Identity.Identity.Models.LoginLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<string>("Ip")
                        .HasColumnType("text")
                        .HasColumnName("ip");

                    b.Property<bool>("IsSuccess")
                        .HasColumnType("boolean")
                        .HasColumnName("is_success");

                    b.Property<DateTime>("LoginTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("login_time");

                    b.Property<string>("LoginType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("login_type");

                    b.Property<string>("Origin")
                        .HasColumnType("text")
                        .HasColumnName("origin");

                    b.Property<string>("Token")
                        .HasColumnType("text")
                        .HasColumnName("token");

                    b.Property<string>("UserAgent")
                        .HasColumnType("text")
                        .HasColumnName("user_agent");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("Username")
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_login_logs");

                    b.ToTable("login_logs", (string)null);
                });

            modelBuilder.Entity("LexiCraft.Services.Identity.Identity.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Avatar")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("avatar");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("create_at");

                    b.Property<Guid?>("CreateById")
                        .HasColumnType("uuid")
                        .HasColumnName("create_by_id");

                    b.Property<string>("CreateByName")
                        .HasColumnType("text")
                        .HasColumnName("create_by_name");

                    b.Property<DateTime?>("DeleteAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("delete_at");

                    b.Property<Guid?>("DeleteById")
                        .HasColumnType("uuid")
                        .HasColumnName("delete_by_id");

                    b.Property<string>("DeleteByName")
                        .HasColumnType("text")
                        .HasColumnName("delete_by_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Phone")
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.PrimitiveCollection<List<string>>("Roles")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("roles");

                    b.Property<Guid?>("SettingsId")
                        .HasColumnType("uuid")
                        .HasColumnName("settings_id");

                    b.Property<string>("Signature")
                        .HasColumnType("text")
                        .HasColumnName("signature");

                    b.Property<int>("Source")
                        .HasColumnType("integer")
                        .HasColumnName("source");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("update_at");

                    b.Property<Guid?>("UpdateById")
                        .HasColumnType("uuid")
                        .HasColumnName("update_by_id");

                    b.Property<string>("UpdateByName")
                        .HasColumnType("text")
                        .HasColumnName("update_by_name");

                    b.Property<string>("UserAccount")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_account");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("SettingsId")
                        .HasDatabaseName("ix_users_settings_id");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("LexiCraft.Services.Identity.Identity.Models.UserOAuth", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AccessToken")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("access_token");

                    b.Property<DateTimeOffset>("AccessTokenExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("access_token_expires_at");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("create_at");

                    b.Property<Guid?>("CreateById")
                        .HasColumnType("uuid")
                        .HasColumnName("create_by_id");

                    b.Property<string>("CreateByName")
                        .HasColumnType("text")
                        .HasColumnName("create_by_name");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("provider");

                    b.Property<string>("ProviderUserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("provider_user_id");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("refresh_token");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("update_at");

                    b.Property<Guid?>("UpdateById")
                        .HasColumnType("uuid")
                        .HasColumnName("update_by_id");

                    b.Property<string>("UpdateByName")
                        .HasColumnType("text")
                        .HasColumnName("update_by_name");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_o_auths");

                    b.ToTable("user_o_auths", (string)null);
                });

            modelBuilder.Entity("LexiCraft.Services.Identity.Identity.Models.UserPermission", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("create_at");

                    b.Property<Guid?>("CreateById")
                        .HasColumnType("uuid")
                        .HasColumnName("create_by_id");

                    b.Property<string>("CreateByName")
                        .HasColumnType("text")
                        .HasColumnName("create_by_name");

                    b.Property<string>("PermissionName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("permission_name");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("update_at");

                    b.Property<Guid?>("UpdateById")
                        .HasColumnType("uuid")
                        .HasColumnName("update_by_id");

                    b.Property<string>("UpdateByName")
                        .HasColumnType("text")
                        .HasColumnName("update_by_name");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_permissions");

                    b.ToTable("user_permissions", (string)null);
                });

            modelBuilder.Entity("LexiCraft.Services.Identity.Identity.Models.UserSetting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("AccountActive")
                        .HasColumnType("boolean")
                        .HasColumnName("account_active");

                    b.Property<bool>("AllowMessages")
                        .HasColumnType("boolean")
                        .HasColumnName("allow_messages");

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("bio");

                    b.Property<DateTime?>("Birthday")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("birthday");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("create_at");

                    b.Property<Guid?>("CreateById")
                        .HasColumnType("uuid")
                        .HasColumnName("create_by_id");

                    b.Property<string>("CreateByName")
                        .HasColumnType("text")
                        .HasColumnName("create_by_name");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("gender");

                    b.Property<bool>("IsProfilePublic")
                        .HasColumnType("boolean")
                        .HasColumnName("is_profile_public");

                    b.Property<bool>("ReceiveEmailUpdates")
                        .HasColumnType("boolean")
                        .HasColumnName("receive_email_updates");

                    b.Property<bool>("ReceiveNotifications")
                        .HasColumnType("boolean")
                        .HasColumnName("receive_notifications");

                    b.Property<bool>("ReceivePushNotifications")
                        .HasColumnType("boolean")
                        .HasColumnName("receive_push_notifications");

                    b.Property<bool>("ShowLearningProgress")
                        .HasColumnType("boolean")
                        .HasColumnName("show_learning_progress");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("update_at");

                    b.Property<Guid?>("UpdateById")
                        .HasColumnType("uuid")
                        .HasColumnName("update_by_id");

                    b.Property<string>("UpdateByName")
                        .HasColumnType("text")
                        .HasColumnName("update_by_name");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_settings");

                    b.ToTable("user_settings", (string)null);
                });

            modelBuilder.Entity("LexiCraft.Services.Identity.Identity.Models.User", b =>
                {
                    b.HasOne("LexiCraft.Services.Identity.Identity.Models.UserSetting", "Settings")
                        .WithMany()
                        .HasForeignKey("SettingsId")
                        .HasConstraintName("fk_users_user_settings_settings_id");

                    b.Navigation("Settings");
                });
#pragma warning restore 612, 618
        }
    }
}
