// <auto-generated />
using System;
using System.Collections.Generic;
using LexiCraft.Services.Vocabulary.Shared.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LexiCraft.Services.Vocabulary.Shared.Data.Migrations
{
    [DbContext(typeof(VocabularyDbContext))]
    partial class VocabularyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LexiCraft.Services.Vocabulary.UserStates.Models.UserWordState", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("create_at");

                    b.Property<Guid?>("CreateById")
                        .HasColumnType("uuid")
                        .HasColumnName("create_by_id");

                    b.Property<string>("CreateByName")
                        .HasColumnType("text")
                        .HasColumnName("create_by_name");

                    b.Property<bool>("IsInWordBook")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_in_word_book")
                        .HasComment("是否在生词本中");

                    b.Property<DateTime?>("LastReviewedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_reviewed_at");

                    b.Property<int>("MasteryScore")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("mastery_score")
                        .HasComment("掌握程度评分");

                    b.Property<int>("State")
                        .HasColumnType("integer")
                        .HasColumnName("state")
                        .HasComment("掌握状态 (0:未学, 1:模糊, 2:掌握)");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("update_at");

                    b.Property<Guid?>("UpdateById")
                        .HasColumnType("uuid")
                        .HasColumnName("update_by_id");

                    b.Property<string>("UpdateByName")
                        .HasColumnType("text")
                        .HasColumnName("update_by_name");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id")
                        .HasComment("用户 ID");

                    b.Property<long>("WordId")
                        .HasColumnType("bigint")
                        .HasColumnName("word_id")
                        .HasComment("单词 ID");

                    b.HasKey("Id")
                        .HasName("pk_user_word_states");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_word_states_user_id");

                    b.HasIndex("UserId", "WordId")
                        .IsUnique()
                        .HasDatabaseName("ix_user_word_states_user_id_word_id");

                    b.ToTable("user_word_states", (string)null);
                });

            modelBuilder.Entity("LexiCraft.Services.Vocabulary.Words.Models.Word", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("create_at");

                    b.Property<Guid?>("CreateById")
                        .HasColumnType("uuid")
                        .HasColumnName("create_by_id");

                    b.Property<string>("CreateByName")
                        .HasColumnType("text")
                        .HasColumnName("create_by_name");

                    b.Property<string>("Definitions")
                        .HasColumnType("jsonb")
                        .HasColumnName("definitions")
                        .HasComment("释义 (JSON)");

                    b.Property<string>("Examples")
                        .HasColumnType("jsonb")
                        .HasColumnName("examples")
                        .HasComment("例句 (JSON)");

                    b.Property<string>("Phonetic")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("phonetic")
                        .HasComment("音标");

                    b.Property<string>("PronunciationUrl")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("pronunciation_url")
                        .HasComment("发音 URL");

                    b.Property<string>("Spelling")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("spelling")
                        .HasComment("单词拼写");

                    b.PrimitiveCollection<List<string>>("Tags")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("tags");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("update_at");

                    b.Property<Guid?>("UpdateById")
                        .HasColumnType("uuid")
                        .HasColumnName("update_by_id");

                    b.Property<string>("UpdateByName")
                        .HasColumnType("text")
                        .HasColumnName("update_by_name");

                    b.HasKey("Id")
                        .HasName("pk_words");

                    b.HasIndex("Spelling")
                        .HasDatabaseName("ix_words_spelling");

                    b.ToTable("words", (string)null);
                });

            modelBuilder.Entity("LexiCraft.Services.Vocabulary.Words.Models.WordList", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("category")
                        .HasComment("分类");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("create_at");

                    b.Property<Guid?>("CreateById")
                        .HasColumnType("uuid")
                        .HasColumnName("create_by_id");

                    b.Property<string>("CreateByName")
                        .HasColumnType("text")
                        .HasColumnName("create_by_name");

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("description")
                        .HasComment("描述");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("name")
                        .HasComment("词库名称");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("update_at");

                    b.Property<Guid?>("UpdateById")
                        .HasColumnType("uuid")
                        .HasColumnName("update_by_id");

                    b.Property<string>("UpdateByName")
                        .HasColumnType("text")
                        .HasColumnName("update_by_name");

                    b.HasKey("Id")
                        .HasName("pk_word_lists");

                    b.ToTable("word_lists", (string)null);
                });

            modelBuilder.Entity("LexiCraft.Services.Vocabulary.Words.Models.WordListItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("create_at");

                    b.Property<Guid?>("CreateById")
                        .HasColumnType("uuid")
                        .HasColumnName("create_by_id");

                    b.Property<string>("CreateByName")
                        .HasColumnType("text")
                        .HasColumnName("create_by_name");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("update_at");

                    b.Property<Guid?>("UpdateById")
                        .HasColumnType("uuid")
                        .HasColumnName("update_by_id");

                    b.Property<string>("UpdateByName")
                        .HasColumnType("text")
                        .HasColumnName("update_by_name");

                    b.Property<long>("WordId")
                        .HasColumnType("bigint")
                        .HasColumnName("word_id");

                    b.Property<long>("WordListId")
                        .HasColumnType("bigint")
                        .HasColumnName("word_list_id");

                    b.HasKey("Id")
                        .HasName("pk_word_list_items");

                    b.HasIndex("WordListId", "WordId")
                        .IsUnique()
                        .HasDatabaseName("ix_word_list_items_word_list_id_word_id");

                    b.ToTable("word_list_items", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
