<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <RootNamespace>BuildingBlocks.Authentication.Redis</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\BuildingBlocks.Authorization\BuildingBlocks.Authorization.csproj"/>
        <ProjectReference Include="..\BuildingBlocks.Caching\BuildingBlocks.Caching.csproj"/>
    </ItemGroup>

</Project>
