<Project Sdk="Microsoft.NET.Sdk.Web">
    <ItemGroup>
        <ProjectReference Include="..\..\..\Fantasy.Aspire.ServiceDefaults\Fantasy.Aspire.ServiceDefaults.csproj"/>
        <ProjectReference Include="..\Fantasy.Services.Identity\Fantasy.Services.Identity.csproj"/>
        <ProjectReference Include="..\..\..\BuildingBlocks\BuildingBlocks.SerilogLogging\BuildingBlocks.SerilogLogging.csproj"/>
        <ProjectReference Include="..\..\..\BuildingBlocks\BuildingBlocks.Caching\BuildingBlocks.Caching.csproj"/>
    </ItemGroup>

</Project>
